### ISSUE TITLE
Wiki update issue and checking there way to navigate directly to entity 

### ISSUE THREAD

**Issue by Learner-121** [microsoft/Dual-write-automations#34]
First of all, thank you for such a great tool.

I am not sure what wrong I am doing, but I am unable to get data/details in the wiki.
![image](https://github.com/microsoft/Dual-write-automations/assets/96948223/57dc2487-7842-4f96-b3bd-ce558bd097ef)

I wanted to check if there is a way I can automatically go to a specific entity. For example, I directly want to run customer group maps.

What could be added to this URL? Can you point where the code is written for this one?

https://dataintegrator.trafficmanager.net/(question:- what to be added )

![image](https://github.com/microsoft/Dual-write-automations/assets/96948223/41bee552-4a73-4f4c-bdfc-cad9f83cdcc6)

@Hax1337

**Comment by Learner-121** [comment]
@Hax1337  please let me know if you have an update here Thank you!

**Comment by Hax1337** [comment]
I see what you mean with the direct URL, there might be a direct URL, I need to check the URL if its feasable. 

For the details, does the user you login have permissons on both CE & FO side?

**Comment by Learner-121** [comment]
Thanks, I am using Admin, so no issues.

How are you able to run the initial sync depending on the config file? Can you help me find that code in repos? I will try to dive deeper to see if I can find it.

I want to be able to directly open the entity-wise view so I can set different automations. In my case, I have a lot of manual efforts, so I want to customize it my own way.

**Comment by Learner-121** [comment]
Hi @Hax1337  Throwing an email on top of your inbox here.

**Comment by Hax1337** [comment]
What would be the use case of customization on the map level? Or whats the manual effort to do there, just out of curiosity?

**Comment by Hax1337** [comment]
Initial sync depending on the config file works with groups, the group can be set on the map level and the group defines if initial sync runs or not. 

https://github.com/microsoft/Dual-write-automations/wiki/02-Main-functionalities-of-the-tool#initial-sync

https://github.com/microsoft/Dual-write-automations/wiki/06---Configuration-options---Configuration-file#section-groups

**Comment by Learner-121** [comment]
@Hax1337  

Thanks for your reply. I am planning to directly run the maps if I have the exact URL. I will create a PowerShell script and add the URLs

Question: As the wiki update is not currently working for me, in the below screenshot, does this wiki URL(link column) section navigate directly to that entity?


![image](https://github.com/microsoft/Dual-write-automations/assets/96948223/6b29923f-531c-4b5f-a0c7-c4b2c7a1f289)

**Comment by Hax1337** [comment]
No, it wont navigate to the entity, it will only navigate to the sub page of the wiki. 

I had another thought about the direct map link and I will look how it would be possible, but I think its gonna be tricky as the authentication needs to happen before.

**Comment by Hax1337** [comment]
I just tested it, when i take the URL from the map details, open a new tab and copy paste it, it wont open. Means directly accessing the map details is not possible

**Comment by Hax1337** [comment]
The inital error was part of the latest version fix:
https://github.com/microsoft/Dual-write-automations/releases/tag/v1.0.7
