### ISSUE TITLE
Error uploading Wiki page if '/' is part of FO entity display name

### ISSUE THREAD

**Issue by soeldk** [microsoft/Dual-write-automations#45]
If the character '/' is part of the displayname in FO, the upload to ADO Wiki fails.

For example if a Country table has been created in CE and a Dual-write map is created between the FO entity 'Country/regions' and the new CE table, it will fail with a message like 'Microsoft.VisualStudio.Services.Common.VssServiceException: One or more ancestor pages of the page '/D365/Dual-write/UAT/DualWrite map configuration/Current maps overview/Country/regions - elem_countries - CURRENT' does not exist.'

It thinks that 'Country' is an ancestorpage to 'regions - elem_countries - CURRENT' rather than 'Current maps overview' is an ancestorpage to 'Country/regions - elem_countries - CURRENT'. 

When generating the link '/' should be changed to something else like '_' or '-'.

**Comment by Hax1337** [comment]
Hi, I fixed this in the latest version!
