### ISSUE TITLE
No template found to apply, using currently applied template

### ISSUE THREAD

**Issue by webyhwh** [microsoft/Dual-write-automations#7]
For each mapping with the version provided in the Map tag there is no template found by the tool.

Looks like the lambda condition in the line below should be changed:
from x => x.version.Equals(build)
to x => x.version.build.Equals(build)

https://github.com/microsoft/Dual-write-automations/blob/96e537bf6ea6bde14868009dc5e65bf8cf759ec7/DWLibary/Engines/DWMapEngine.cs#LL1921C17-L1921C17

**Comment by Hax1337** [comment]
thanks @webyhwh, will be fixed shortly
